### ISSUE TITLE
Return statement for \CodeEdu\FixtureCommand::execute method

### ISSUE THREAD

**Issue by bagardavidyanisntreal** [codeedu/zendexpr-doctrine-fixture#1]
pls add a return statement (suggested 0) to method implementation, because of the parent
now I got the err:
```
PHP Fatal error:  Uncaught TypeError: Return value of "CodeEdu\FixtureCommand::execute()" must be of the type int, NULL returned. in /var/www/test-zend/vendor/symfony/console/Command/Command.php:258
Stack trace:
#0 /var/www/test-zend/vendor/symfony/console/Application.php(924): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /var/www/test-zend/vendor/symfony/console/Application.php(265): Symfony\Component\Console\Application->doRunCommand(Object(CodeEdu\FixtureCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/test-zend/vendor/symfony/console/Application.php(141): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/test-zend/bin/console.php(18): Symfony\Component\Console\Application->run()
#4 {main}
  thrown in /var/www/test-zend/vendor/symfony/console/Command/Command.php on line 258
```

**Comment by argentinaluiz** [comment]
Hi, @DavidBagaryan 

What version of php are you using?

**Comment by bagardavidyanisntreal** [comment]
Hi @argentinaluiz!
Thanks for the fast reply, I'm on PHP 7.3  
I've fixed this by extending the base FixtureFactory and FixtureCommand, but I find this a little unflexible.

**Comment by argentinaluiz** [comment]
I will check it.

When I updated the package, the latest version was 7.1.

Thanks for you feedback.

**Comment by PoetikDragon** [comment]
Having the same error

**Comment by argentinaluiz** [comment]
Hi @PoetikDragon ,

I already fix this bug. Could share me a example repo with error?

**Comment by PoetikDragon** [comment]
@argentinaluiz I don't know where you fixed it, since the code here hasn't been touched since July of 2019. But anyway I submitted a pull request with the fix.

**Comment by argentinaluiz** [comment]
@PoetikDragon Thanks for you help.
